           
diagram_fact(align, cell_10, "center").
diagram_fact(align, cell_11, "left").
diagram_fact(align, cell_12, "center").
diagram_fact(align, cell_13, "center").
diagram_fact(align, cell_14, "center").
diagram_fact(align, cell_15, "center").
diagram_fact(align, cell_16, "center").
diagram_fact(align, cell_17, "center").
diagram_fact(align, cell_18, "center").
diagram_fact(align, cell_19, "left").
diagram_fact(align, cell_20, "center").
diagram_fact(align, cell_21, "center").
diagram_fact(align, cell_22, "center").
diagram_fact(align, cell_23, "center").
diagram_fact(align, cell_24, "center").
diagram_fact(align, cell_25, "center").
diagram_fact(align, cell_26, "center").
diagram_fact(align, cell_27, "left").
diagram_fact(align, cell_28, "center").
diagram_fact(align, cell_29, "center").
diagram_fact(align, cell_30, "center").
diagram_fact(align, cell_31, "center").
diagram_fact(align, cell_32, "center").
diagram_fact(align, cell_33, "center").
diagram_fact(align, cell_34, "left").
diagram_fact(align, cell_35, "center").
diagram_fact(align, cell_36, "center").
diagram_fact(align, cell_38, "center").
diagram_fact(align, cell_40, "center").
diagram_fact(align, cell_41, "center").
diagram_fact(align, cell_7, "center").
diagram_fact(align, cell_8, "center").
diagram_fact(align, cell_9, "center").
diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_19, "geometry").
diagram_fact(as, cell_20, "geometry").
diagram_fact(as, cell_21, "geometry").
diagram_fact(as, cell_22, "geometry").
diagram_fact(as, cell_23, "geometry").
diagram_fact(as, cell_24, "geometry").
diagram_fact(as, cell_25, "geometry").
diagram_fact(as, cell_26, "geometry").
diagram_fact(as, cell_27, "geometry").
diagram_fact(as, cell_28, "geometry").
diagram_fact(as, cell_29, "geometry").
diagram_fact(as, cell_30, "geometry").
diagram_fact(as, cell_31, "geometry").
diagram_fact(as, cell_32, "geometry").
diagram_fact(as, cell_33, "geometry").
diagram_fact(as, cell_34, "geometry").
diagram_fact(as, cell_35, "geometry").
diagram_fact(as, cell_36, "geometry").
diagram_fact(as, cell_37, "geometry").
diagram_fact(as, cell_38, "geometry").
diagram_fact(as, cell_39, "geometry").
diagram_fact(as, cell_40, "geometry").
diagram_fact(as, cell_41, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(aspect, cell_10, "fixed").
diagram_fact(aspect, cell_13, "fixed").
diagram_fact(aspect, cell_14, "fixed").
diagram_fact(aspect, cell_16, "fixed").
diagram_fact(aspect, cell_18, "fixed").
diagram_fact(aspect, cell_21, "fixed").
diagram_fact(aspect, cell_22, "fixed").
diagram_fact(aspect, cell_24, "fixed").
diagram_fact(aspect, cell_26, "fixed").
diagram_fact(aspect, cell_29, "fixed").
diagram_fact(aspect, cell_30, "fixed").
diagram_fact(aspect, cell_32, "fixed").
diagram_fact(aspect, cell_33, "fixed").
diagram_fact(aspect, cell_35, "fixed").
diagram_fact(aspect, cell_36, "fixed").
diagram_fact(aspect, cell_38, "fixed").
diagram_fact(aspect, cell_40, "fixed").
diagram_fact(aspect, cell_41, "fixed").
diagram_fact(aspect, cell_8, "fixed").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_19, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_21, "").
diagram_fact(cell, cell_22, "").
diagram_fact(cell, cell_23, "").
diagram_fact(cell, cell_24, "").
diagram_fact(cell, cell_25, "").
diagram_fact(cell, cell_26, "").
diagram_fact(cell, cell_27, "").
diagram_fact(cell, cell_28, "").
diagram_fact(cell, cell_29, "").
diagram_fact(cell, cell_30, "").
diagram_fact(cell, cell_31, "").
diagram_fact(cell, cell_32, "").
diagram_fact(cell, cell_33, "").
diagram_fact(cell, cell_34, "").
diagram_fact(cell, cell_35, "").
diagram_fact(cell, cell_36, "").
diagram_fact(cell, cell_37, "").
diagram_fact(cell, cell_38, "").
diagram_fact(cell, cell_39, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_40, "").
diagram_fact(cell, cell_41, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_9, "").
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_12, 1).
diagram_fact(edge, cell_17, 1).
diagram_fact(edge, cell_20, 1).
diagram_fact(edge, cell_25, 1).
diagram_fact(edge, cell_28, 1).
diagram_fact(edge, cell_37, 1).
diagram_fact(edge, cell_39, 1).
diagram_fact(edge, cell_9, 1).
diagram_fact(edgeStyle, cell_12, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_17, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_20, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_25, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_28, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_37, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_39, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_9, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_12, 0).
diagram_fact(entryDx, cell_25, 0).
diagram_fact(entryDx, cell_28, 0).
diagram_fact(entryDx, cell_37, 0).
diagram_fact(entryDx, cell_39, 0).
diagram_fact(entryDx, cell_9, 0).
diagram_fact(entryDy, cell_12, 0).
diagram_fact(entryDy, cell_25, 0).
diagram_fact(entryDy, cell_28, 0).
diagram_fact(entryDy, cell_37, 0).
diagram_fact(entryDy, cell_39, 0).
diagram_fact(entryDy, cell_9, 0).
diagram_fact(entryX, cell_12, 0).
diagram_fact(entryX, cell_25, 0).
diagram_fact(entryX, cell_28, 0).
diagram_fact(entryX, cell_37, 0).
diagram_fact(entryX, cell_39, 0).
diagram_fact(entryX, cell_9, 0).
diagram_fact(entryY, cell_12, 0.5).
diagram_fact(entryY, cell_25, 0.5).
diagram_fact(entryY, cell_28, 0.5).
diagram_fact(entryY, cell_37, 0.5).
diagram_fact(entryY, cell_39, 0.5).
diagram_fact(entryY, cell_9, 0.5).
diagram_fact(exitDx, cell_12, 0).
diagram_fact(exitDx, cell_17, 0).
diagram_fact(exitDx, cell_20, 0).
diagram_fact(exitDx, cell_25, 0).
diagram_fact(exitDx, cell_28, 0).
diagram_fact(exitDx, cell_37, 0).
diagram_fact(exitDx, cell_39, 0).
diagram_fact(exitDx, cell_9, 0).
diagram_fact(exitDy, cell_12, 0).
diagram_fact(exitDy, cell_17, 0).
diagram_fact(exitDy, cell_20, 0).
diagram_fact(exitDy, cell_25, 0).
diagram_fact(exitDy, cell_28, 0).
diagram_fact(exitDy, cell_37, 0).
diagram_fact(exitDy, cell_39, 0).
diagram_fact(exitDy, cell_9, 0).
diagram_fact(exitX, cell_12, 1).
diagram_fact(exitX, cell_17, 1).
diagram_fact(exitX, cell_20, 1).
diagram_fact(exitX, cell_25, 1).
diagram_fact(exitX, cell_28, 1).
diagram_fact(exitX, cell_37, 1).
diagram_fact(exitX, cell_39, 1).
diagram_fact(exitX, cell_9, 1).
diagram_fact(exitY, cell_12, 0.5).
diagram_fact(exitY, cell_17, 0.5).
diagram_fact(exitY, cell_20, 0.5).
diagram_fact(exitY, cell_25, 0.5).
diagram_fact(exitY, cell_28, 0.5).
diagram_fact(exitY, cell_37, 0.5).
diagram_fact(exitY, cell_39, 0.5).
diagram_fact(exitY, cell_9, 0.5).
diagram_fact(fillColor, cell_10, "#fff2cc").
diagram_fact(fillColor, cell_11, "#f8cecc").
diagram_fact(fillColor, cell_13, "#fff2cc").
diagram_fact(fillColor, cell_14, "#d5e8d4").
diagram_fact(fillColor, cell_16, "#d5e8d4").
diagram_fact(fillColor, cell_18, "#fff2cc").
diagram_fact(fillColor, cell_19, "#f8cecc").
diagram_fact(fillColor, cell_21, "#fff2cc").
diagram_fact(fillColor, cell_22, "#d5e8d4").
diagram_fact(fillColor, cell_24, "#d5e8d4").
diagram_fact(fillColor, cell_26, "#fff2cc").
diagram_fact(fillColor, cell_27, "#f8cecc").
diagram_fact(fillColor, cell_29, "#fff2cc").
diagram_fact(fillColor, cell_30, "#d5e8d4").
diagram_fact(fillColor, cell_32, "#d5e8d4").
diagram_fact(fillColor, cell_33, "#fff2cc").
diagram_fact(fillColor, cell_34, "#f8cecc").
diagram_fact(fillColor, cell_35, "#fff2cc").
diagram_fact(fillColor, cell_36, "#d5e8d4").
diagram_fact(fillColor, cell_38, "#d5e8d4").
diagram_fact(fillColor, cell_40, "#d5e8d4").
diagram_fact(fillColor, cell_41, "#fff2cc").
diagram_fact(fillColor, cell_8, "#d5e8d4").
diagram_fact(height, cell_10, 40).
diagram_fact(height, cell_11, 35).
diagram_fact(height, cell_13, 40).
diagram_fact(height, cell_14, 40).
diagram_fact(height, cell_15, 170).
diagram_fact(height, cell_16, 40).
diagram_fact(height, cell_18, 40).
diagram_fact(height, cell_19, 35).
diagram_fact(height, cell_21, 40).
diagram_fact(height, cell_22, 40).
diagram_fact(height, cell_23, 170).
diagram_fact(height, cell_24, 40).
diagram_fact(height, cell_26, 40).
diagram_fact(height, cell_27, 35).
diagram_fact(height, cell_29, 40).
diagram_fact(height, cell_30, 40).
diagram_fact(height, cell_31, 170).
diagram_fact(height, cell_32, 40).
diagram_fact(height, cell_33, 40).
diagram_fact(height, cell_34, 35).
diagram_fact(height, cell_35, 40).
diagram_fact(height, cell_36, 40).
diagram_fact(height, cell_38, 40).
diagram_fact(height, cell_40, 40).
diagram_fact(height, cell_41, 40).
diagram_fact(height, cell_6, 1160).
diagram_fact(height, cell_7, 170).
diagram_fact(height, cell_8, 40).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_19, 1).
diagram_fact(html, cell_20, 1).
diagram_fact(html, cell_21, 1).
diagram_fact(html, cell_22, 1).
diagram_fact(html, cell_23, 1).
diagram_fact(html, cell_24, 1).
diagram_fact(html, cell_25, 1).
diagram_fact(html, cell_26, 1).
diagram_fact(html, cell_27, 1).
diagram_fact(html, cell_28, 1).
diagram_fact(html, cell_29, 1).
diagram_fact(html, cell_30, 1).
diagram_fact(html, cell_31, 1).
diagram_fact(html, cell_32, 1).
diagram_fact(html, cell_33, 1).
diagram_fact(html, cell_34, 1).
diagram_fact(html, cell_35, 1).
diagram_fact(html, cell_36, 1).
diagram_fact(html, cell_37, 1).
diagram_fact(html, cell_38, 1).
diagram_fact(html, cell_39, 1).
diagram_fact(html, cell_40, 1).
diagram_fact(html, cell_41, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(jettySize, cell_12, "auto").
diagram_fact(jettySize, cell_17, "auto").
diagram_fact(jettySize, cell_20, "auto").
diagram_fact(jettySize, cell_25, "auto").
diagram_fact(jettySize, cell_28, "auto").
diagram_fact(jettySize, cell_37, "auto").
diagram_fact(jettySize, cell_39, "auto").
diagram_fact(jettySize, cell_9, "auto").
diagram_fact(kind, cell_10, "ellipse").
diagram_fact(kind, cell_13, "ellipse").
diagram_fact(kind, cell_14, "ellipse").
diagram_fact(kind, cell_16, "ellipse").
diagram_fact(kind, cell_18, "ellipse").
diagram_fact(kind, cell_21, "ellipse").
diagram_fact(kind, cell_22, "ellipse").
diagram_fact(kind, cell_24, "ellipse").
diagram_fact(kind, cell_26, "ellipse").
diagram_fact(kind, cell_29, "ellipse").
diagram_fact(kind, cell_30, "ellipse").
diagram_fact(kind, cell_32, "ellipse").
diagram_fact(kind, cell_33, "ellipse").
diagram_fact(kind, cell_35, "ellipse").
diagram_fact(kind, cell_36, "ellipse").
diagram_fact(kind, cell_38, "ellipse").
diagram_fact(kind, cell_40, "ellipse").
diagram_fact(kind, cell_41, "ellipse").
diagram_fact(kind, cell_8, "ellipse").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "testbench").
diagram_fact(orthogonalLoop, cell_12, 1).
diagram_fact(orthogonalLoop, cell_17, 1).
diagram_fact(orthogonalLoop, cell_20, 1).
diagram_fact(orthogonalLoop, cell_25, 1).
diagram_fact(orthogonalLoop, cell_28, 1).
diagram_fact(orthogonalLoop, cell_37, 1).
diagram_fact(orthogonalLoop, cell_39, 1).
diagram_fact(orthogonalLoop, cell_9, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_19, id_1).
diagram_fact(parent, cell_20, id_1).
diagram_fact(parent, cell_21, id_1).
diagram_fact(parent, cell_22, id_1).
diagram_fact(parent, cell_23, id_1).
diagram_fact(parent, cell_24, id_1).
diagram_fact(parent, cell_25, id_1).
diagram_fact(parent, cell_26, id_1).
diagram_fact(parent, cell_27, id_1).
diagram_fact(parent, cell_28, id_1).
diagram_fact(parent, cell_29, id_1).
diagram_fact(parent, cell_30, id_1).
diagram_fact(parent, cell_31, id_1).
diagram_fact(parent, cell_32, id_1).
diagram_fact(parent, cell_33, id_1).
diagram_fact(parent, cell_34, id_1).
diagram_fact(parent, cell_35, id_1).
diagram_fact(parent, cell_36, id_1).
diagram_fact(parent, cell_37, id_1).
diagram_fact(parent, cell_38, id_1).
diagram_fact(parent, cell_39, id_1).
diagram_fact(parent, cell_40, id_1).
diagram_fact(parent, cell_41, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(relative, cell_12, 1).
diagram_fact(relative, cell_17, 1).
diagram_fact(relative, cell_20, 1).
diagram_fact(relative, cell_25, 1).
diagram_fact(relative, cell_28, 1).
diagram_fact(relative, cell_37, 1).
diagram_fact(relative, cell_39, 1).
diagram_fact(relative, cell_9, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_11, 0).
diagram_fact(rounded, cell_12, 0).
diagram_fact(rounded, cell_15, 1).
diagram_fact(rounded, cell_17, 0).
diagram_fact(rounded, cell_19, 0).
diagram_fact(rounded, cell_20, 0).
diagram_fact(rounded, cell_23, 1).
diagram_fact(rounded, cell_25, 0).
diagram_fact(rounded, cell_27, 0).
diagram_fact(rounded, cell_28, 0).
diagram_fact(rounded, cell_31, 1).
diagram_fact(rounded, cell_34, 0).
diagram_fact(rounded, cell_37, 0).
diagram_fact(rounded, cell_39, 0).
diagram_fact(rounded, cell_6, 1).
diagram_fact(rounded, cell_7, 1).
diagram_fact(rounded, cell_9, 0).
diagram_fact(source, cell_12, id_CUezxsRruvy4vppBqpLz__7).
diagram_fact(source, cell_17, id_CUezxsRruvy4vppBqpLz__15).
diagram_fact(source, cell_20, id_CUezxsRruvy4vppBqpLz__18).
diagram_fact(source, cell_25, id_CUezxsRruvy4vppBqpLz__24).
diagram_fact(source, cell_28, id_CUezxsRruvy4vppBqpLz__27).
diagram_fact(source, cell_37, id_CUezxsRruvy4vppBqpLz__40).
diagram_fact(source, cell_39, id_CUezxsRruvy4vppBqpLz__41).
diagram_fact(source, cell_9, id_CUezxsRruvy4vppBqpLz__4).
diagram_fact(spacingLeft, cell_11, 5).
diagram_fact(spacingLeft, cell_19, 5).
diagram_fact(spacingLeft, cell_27, 5).
diagram_fact(spacingLeft, cell_34, 5).
diagram_fact(strokeColor, cell_10, "#d6b656").
diagram_fact(strokeColor, cell_11, "#b85450").
diagram_fact(strokeColor, cell_13, "#d6b656").
diagram_fact(strokeColor, cell_14, "#82b366").
diagram_fact(strokeColor, cell_16, "#82b366").
diagram_fact(strokeColor, cell_18, "#d6b656").
diagram_fact(strokeColor, cell_19, "#b85450").
diagram_fact(strokeColor, cell_21, "#d6b656").
diagram_fact(strokeColor, cell_22, "#82b366").
diagram_fact(strokeColor, cell_24, "#82b366").
diagram_fact(strokeColor, cell_26, "#d6b656").
diagram_fact(strokeColor, cell_27, "#b85450").
diagram_fact(strokeColor, cell_29, "#d6b656").
diagram_fact(strokeColor, cell_30, "#82b366").
diagram_fact(strokeColor, cell_32, "#82b366").
diagram_fact(strokeColor, cell_33, "#d6b656").
diagram_fact(strokeColor, cell_34, "#b85450").
diagram_fact(strokeColor, cell_35, "#d6b656").
diagram_fact(strokeColor, cell_36, "#82b366").
diagram_fact(strokeColor, cell_38, "#82b366").
diagram_fact(strokeColor, cell_40, "#82b366").
diagram_fact(strokeColor, cell_41, "#d6b656").
diagram_fact(strokeColor, cell_8, "#82b366").
diagram_fact(synonym, cell_10, id_CUezxsRruvy4vppBqpLz__4).
diagram_fact(synonym, cell_11, id_CUezxsRruvy4vppBqpLz__5).
diagram_fact(synonym, cell_12, id_CUezxsRruvy4vppBqpLz__6).
diagram_fact(synonym, cell_13, id_CUezxsRruvy4vppBqpLz__7).
diagram_fact(synonym, cell_14, id_CUezxsRruvy4vppBqpLz__8).
diagram_fact(synonym, cell_15, id_CUezxsRruvy4vppBqpLz__12).
diagram_fact(synonym, cell_16, id_CUezxsRruvy4vppBqpLz__13).
diagram_fact(synonym, cell_17, id_CUezxsRruvy4vppBqpLz__14).
diagram_fact(synonym, cell_18, id_CUezxsRruvy4vppBqpLz__15).
diagram_fact(synonym, cell_19, id_CUezxsRruvy4vppBqpLz__16).
diagram_fact(synonym, cell_20, id_CUezxsRruvy4vppBqpLz__17).
diagram_fact(synonym, cell_21, id_CUezxsRruvy4vppBqpLz__18).
diagram_fact(synonym, cell_22, id_CUezxsRruvy4vppBqpLz__19).
diagram_fact(synonym, cell_23, id_CUezxsRruvy4vppBqpLz__21).
diagram_fact(synonym, cell_24, id_CUezxsRruvy4vppBqpLz__22).
diagram_fact(synonym, cell_25, id_CUezxsRruvy4vppBqpLz__23).
diagram_fact(synonym, cell_26, id_CUezxsRruvy4vppBqpLz__24).
diagram_fact(synonym, cell_27, id_CUezxsRruvy4vppBqpLz__25).
diagram_fact(synonym, cell_28, id_CUezxsRruvy4vppBqpLz__26).
diagram_fact(synonym, cell_29, id_CUezxsRruvy4vppBqpLz__27).
diagram_fact(synonym, cell_30, id_CUezxsRruvy4vppBqpLz__28).
diagram_fact(synonym, cell_31, id_CUezxsRruvy4vppBqpLz__30).
diagram_fact(synonym, cell_32, id_CUezxsRruvy4vppBqpLz__31).
diagram_fact(synonym, cell_33, id_CUezxsRruvy4vppBqpLz__32).
diagram_fact(synonym, cell_34, id_CUezxsRruvy4vppBqpLz__33).
diagram_fact(synonym, cell_35, id_CUezxsRruvy4vppBqpLz__34).
diagram_fact(synonym, cell_36, id_CUezxsRruvy4vppBqpLz__35).
diagram_fact(synonym, cell_37, id_CUezxsRruvy4vppBqpLz__42).
diagram_fact(synonym, cell_38, id_CUezxsRruvy4vppBqpLz__40).
diagram_fact(synonym, cell_39, id_CUezxsRruvy4vppBqpLz__43).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_40, id_CUezxsRruvy4vppBqpLz__41).
diagram_fact(synonym, cell_41, id_CUezxsRruvy4vppBqpLz__44).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_6, id_CUezxsRruvy4vppBqpLz__37).
diagram_fact(synonym, cell_7, id_CUezxsRruvy4vppBqpLz__1).
diagram_fact(synonym, cell_8, id_CUezxsRruvy4vppBqpLz__2).
diagram_fact(synonym, cell_9, id_CUezxsRruvy4vppBqpLz__3).
diagram_fact(target, cell_12, id_CUezxsRruvy4vppBqpLz__19).
diagram_fact(target, cell_17, id_CUezxsRruvy4vppBqpLz__22).
diagram_fact(target, cell_20, id_CUezxsRruvy4vppBqpLz__28).
diagram_fact(target, cell_25, id_CUezxsRruvy4vppBqpLz__31).
diagram_fact(target, cell_28, id_CUezxsRruvy4vppBqpLz__35).
diagram_fact(target, cell_37, id_CUezxsRruvy4vppBqpLz__2).
diagram_fact(target, cell_39, id_CUezxsRruvy4vppBqpLz__8).
diagram_fact(target, cell_9, id_CUezxsRruvy4vppBqpLz__13).
diagram_fact(value, cell_10, "env").
diagram_fact(value, cell_11, "&lt;span style=&quot;text-align: center&quot;&gt;❮&lt;/span&gt;&amp;nbsp; for each file in '&lt;span style=&quot;font-size: 11px&quot;&gt;/Users/tarvydas/temp/ps/@book-Hamburger Workbench - A Frivolous Introduction to Ohm-JS'&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 11px&quot;&gt;⇉ «f»&amp;nbsp;&lt;/span&gt;❯").
diagram_fact(value, cell_13, "baton").
diagram_fact(value, cell_14, "baton").
diagram_fact(value, cell_15, "noname_1").
diagram_fact(value, cell_16, "env").
diagram_fact(value, cell_18, "env").
diagram_fact(value, cell_19, "&lt;span style=&quot;text-align: center&quot;&gt;❮&lt;/span&gt;&lt;span style=&quot;font-size: 11px&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;color: rgb(51 , 51 , 51)&quot;&gt;delete all files in &quot;/tmp/iwantahamburger&quot;&amp;nbsp;&lt;/span&gt;❯").
diagram_fact(value, cell_21, "baton").
diagram_fact(value, cell_22, "baton").
diagram_fact(value, cell_23, "noname_2").
diagram_fact(value, cell_24, "env").
diagram_fact(value, cell_26, "env").
diagram_fact(value, cell_27, "&lt;span style=&quot;text-align: center&quot;&gt;❮&lt;/span&gt;&lt;span style=&quot;font-size: 11px&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;color: rgb(51 , 51 , 51)&quot;&gt;copy «f» to &quot;/tmp/iwantahamburger&quot;&amp;nbsp;&lt;/span&gt;❯").
diagram_fact(value, cell_29, "baton").
diagram_fact(value, cell_30, "baton").
diagram_fact(value, cell_31, "noname_3").
diagram_fact(value, cell_32, "env").
diagram_fact(value, cell_33, "env").
diagram_fact(value, cell_34, "&lt;div&gt;❮ rename &quot;/tmp/iwantahamburger/hw_book.md&quot; &quot;/tmp/iwantahamburger/book.md&quot; ❯&lt;/div&gt;").
diagram_fact(value, cell_35, "baton").
diagram_fact(value, cell_36, "baton").
diagram_fact(value, cell_38, "env").
diagram_fact(value, cell_40, "baton").
diagram_fact(value, cell_41, "out").
diagram_fact(value, cell_6, "script").
diagram_fact(value, cell_7, "noname_0").
diagram_fact(value, cell_8, "env").
diagram_fact(vertex, cell_10, 1).
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_14, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_16, 1).
diagram_fact(vertex, cell_18, 1).
diagram_fact(vertex, cell_19, 1).
diagram_fact(vertex, cell_21, 1).
diagram_fact(vertex, cell_22, 1).
diagram_fact(vertex, cell_23, 1).
diagram_fact(vertex, cell_24, 1).
diagram_fact(vertex, cell_26, 1).
diagram_fact(vertex, cell_27, 1).
diagram_fact(vertex, cell_29, 1).
diagram_fact(vertex, cell_30, 1).
diagram_fact(vertex, cell_31, 1).
diagram_fact(vertex, cell_32, 1).
diagram_fact(vertex, cell_33, 1).
diagram_fact(vertex, cell_34, 1).
diagram_fact(vertex, cell_35, 1).
diagram_fact(vertex, cell_36, 1).
diagram_fact(vertex, cell_38, 1).
diagram_fact(vertex, cell_40, 1).
diagram_fact(vertex, cell_41, 1).
diagram_fact(vertex, cell_6, 1).
diagram_fact(vertex, cell_7, 1).
diagram_fact(vertex, cell_8, 1).
diagram_fact(verticalAlign, cell_15, "top").
diagram_fact(verticalAlign, cell_23, "top").
diagram_fact(verticalAlign, cell_31, "top").
diagram_fact(verticalAlign, cell_6, "top").
diagram_fact(verticalAlign, cell_7, "top").
diagram_fact(whiteSpace, cell_10, "wrap").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_14, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_16, "wrap").
diagram_fact(whiteSpace, cell_18, "wrap").
diagram_fact(whiteSpace, cell_19, "wrap").
diagram_fact(whiteSpace, cell_21, "wrap").
diagram_fact(whiteSpace, cell_22, "wrap").
diagram_fact(whiteSpace, cell_23, "wrap").
diagram_fact(whiteSpace, cell_24, "wrap").
diagram_fact(whiteSpace, cell_26, "wrap").
diagram_fact(whiteSpace, cell_27, "wrap").
diagram_fact(whiteSpace, cell_29, "wrap").
diagram_fact(whiteSpace, cell_30, "wrap").
diagram_fact(whiteSpace, cell_31, "wrap").
diagram_fact(whiteSpace, cell_32, "wrap").
diagram_fact(whiteSpace, cell_33, "wrap").
diagram_fact(whiteSpace, cell_34, "wrap").
diagram_fact(whiteSpace, cell_35, "wrap").
diagram_fact(whiteSpace, cell_36, "wrap").
diagram_fact(whiteSpace, cell_38, "wrap").
diagram_fact(whiteSpace, cell_40, "wrap").
diagram_fact(whiteSpace, cell_41, "wrap").
diagram_fact(whiteSpace, cell_6, "wrap").
diagram_fact(whiteSpace, cell_7, "wrap").
diagram_fact(whiteSpace, cell_8, "wrap").
diagram_fact(width, cell_10, 40).
diagram_fact(width, cell_11, 570).
diagram_fact(width, cell_13, 40).
diagram_fact(width, cell_14, 40).
diagram_fact(width, cell_15, 640).
diagram_fact(width, cell_16, 40).
diagram_fact(width, cell_18, 40).
diagram_fact(width, cell_19, 570).
diagram_fact(width, cell_21, 40).
diagram_fact(width, cell_22, 40).
diagram_fact(width, cell_23, 640).
diagram_fact(width, cell_24, 40).
diagram_fact(width, cell_26, 40).
diagram_fact(width, cell_27, 570).
diagram_fact(width, cell_29, 40).
diagram_fact(width, cell_30, 40).
diagram_fact(width, cell_31, 700).
diagram_fact(width, cell_32, 40).
diagram_fact(width, cell_33, 40).
diagram_fact(width, cell_34, 625).
diagram_fact(width, cell_35, 40).
diagram_fact(width, cell_36, 40).
diagram_fact(width, cell_38, 40).
diagram_fact(width, cell_40, 40).
diagram_fact(width, cell_41, 40).
diagram_fact(width, cell_6, 950).
diagram_fact(width, cell_7, 640).
diagram_fact(width, cell_8, 40).
diagram_fact(x, cell_10, 790).
diagram_fact(x, cell_11, 205).
diagram_fact(x, cell_13, 790).
diagram_fact(x, cell_14, 150).
diagram_fact(x, cell_15, 170).
diagram_fact(x, cell_16, 150).
diagram_fact(x, cell_18, 790).
diagram_fact(x, cell_19, 205).
diagram_fact(x, cell_21, 790).
diagram_fact(x, cell_22, 150).
diagram_fact(x, cell_23, 170).
diagram_fact(x, cell_24, 150).
diagram_fact(x, cell_26, 790).
diagram_fact(x, cell_27, 205).
diagram_fact(x, cell_29, 790).
diagram_fact(x, cell_30, 150).
diagram_fact(x, cell_31, 170).
diagram_fact(x, cell_32, 150).
diagram_fact(x, cell_33, 850).
diagram_fact(x, cell_34, 205).
diagram_fact(x, cell_35, 850).
diagram_fact(x, cell_36, 150).
diagram_fact(x, cell_38, 20).
diagram_fact(x, cell_40, 20).
diagram_fact(x, cell_41, 970).
diagram_fact(x, cell_6, 40).
diagram_fact(x, cell_7, 170).
diagram_fact(x, cell_8, 150).
diagram_fact(y, cell_10, 235).
diagram_fact(y, cell_11, 300).
diagram_fact(y, cell_13, 295).
diagram_fact(y, cell_14, 295).
diagram_fact(y, cell_15, 470).
diagram_fact(y, cell_16, 505).
diagram_fact(y, cell_18, 505).
diagram_fact(y, cell_19, 570).
diagram_fact(y, cell_21, 565).
diagram_fact(y, cell_22, 565).
diagram_fact(y, cell_23, 730).
diagram_fact(y, cell_24, 765).
diagram_fact(y, cell_26, 765).
diagram_fact(y, cell_27, 830).
diagram_fact(y, cell_29, 825).
diagram_fact(y, cell_30, 825).
diagram_fact(y, cell_31, 1020).
diagram_fact(y, cell_32, 1055).
diagram_fact(y, cell_33, 1050).
diagram_fact(y, cell_34, 1120).
diagram_fact(y, cell_35, 1110).
diagram_fact(y, cell_36, 1115).
diagram_fact(y, cell_38, 235).
diagram_fact(y, cell_40, 295).
diagram_fact(y, cell_41, 1015).
diagram_fact(y, cell_6, 120).
diagram_fact(y, cell_7, 200).
diagram_fact(y, cell_8, 235).
