(defun stack-test ()
  (let ((stack (new-stack)))
    (@ stack 'push 1)
    (@ stack 'push 2)
    (@ stack 'push 3)
    (let ((rfirst (@ stack 'pop)))
      (let ((rsecond (@ stack 'pop)))
        (list rfirst rsecond stack)))))

(defun queue-test ()
  (let ((q (new-queue)))
    (@ q 'enqueue 1)
    (@ q 'enqueue 2)
    (@ q 'enqueue 3)
    (let ((rfirst (@ q 'dequeue)))
      (let ((rsecond (@ q 'dequeue)))
        (list rfirst rsecond q)))))

(defun test ()
  (let ((sresult (stack-test)))
    (let ((qresult (queue-test)))
      (list sresult qresult))))
